# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tribometroPinOnDisk.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1347, 853)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color:rgb(20,49,83);\n"
"border radius:12px; ")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(10, 0, 9, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_superior = QtWidgets.QFrame(self.frame)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_superior.setStyleSheet("Qframe{\n"
"background-color:rgb(102,112,128);\n"
"}\n"
"QPushButton{\n"
"border radius:11px;\n"
"background-color:rgb(243,249,249);\n"
"}\n"
"QPushButtonchover{\n"
"background-color:rgb(243,249,249);\n"
"}")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.frame_superior)
        self.label_9.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 87 12pt \"Arial Black\";\n"
"")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        spacerItem = QtWidgets.QSpacerItem(1119, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.bt_minimize = QtWidgets.QPushButton(self.frame_superior)
        self.bt_minimize.setMinimumSize(QtCore.QSize(38, 30))
        self.bt_minimize.setMaximumSize(QtCore.QSize(38, 30))
        self.bt_minimize.setWhatsThis("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Minimizar/Imagenes/minimizar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_minimize.setIcon(icon)
        self.bt_minimize.setIconSize(QtCore.QSize(16, 16))
        self.bt_minimize.setObjectName("bt_minimize")
        self.horizontalLayout_2.addWidget(self.bt_minimize)
        self.bt_maximize = QtWidgets.QPushButton(self.frame_superior)
        self.bt_maximize.setMinimumSize(QtCore.QSize(38, 30))
        self.bt_maximize.setMaximumSize(QtCore.QSize(38, 30))
        self.bt_maximize.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Tamaño/Imagenes/resize_minimize_maximize_expand_screen_icon_190599.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_maximize.setIcon(icon1)
        self.bt_maximize.setIconSize(QtCore.QSize(16, 16))
        self.bt_maximize.setObjectName("bt_maximize")
        self.horizontalLayout_2.addWidget(self.bt_maximize)
        self.bt_normal = QtWidgets.QPushButton(self.frame_superior)
        self.bt_normal.setMinimumSize(QtCore.QSize(38, 30))
        self.bt_normal.setMaximumSize(QtCore.QSize(38, 30))
        self.bt_normal.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Tamaño/Imagenes/resize_minimize_maximize_expand_screen_icon_190627.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_normal.setIcon(icon2)
        self.bt_normal.setIconSize(QtCore.QSize(16, 16))
        self.bt_normal.setObjectName("bt_normal")
        self.horizontalLayout_2.addWidget(self.bt_normal)
        self.bt_close = QtWidgets.QPushButton(self.frame_superior)
        self.bt_close.setMinimumSize(QtCore.QSize(38, 30))
        self.bt_close.setMaximumSize(QtCore.QSize(38, 30))
        self.bt_close.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Cerrar/Imagenes/Cerrar.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_close.setIcon(icon3)
        self.bt_close.setIconSize(QtCore.QSize(16, 16))
        self.bt_close.setObjectName("bt_close")
        self.horizontalLayout_2.addWidget(self.bt_close)
        self.verticalLayout.addWidget(self.frame_superior)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setStyleSheet("background-color:rgb(245,248,246);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frame_7 = QtWidgets.QFrame(self.frame_8)
        self.frame_7.setStyleSheet("background-color:rgb(245,248,246);\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setStyleSheet("color:rgb();\n"
"font: 87 12pt \"Arial Black\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_12.addWidget(self.label_5)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.frame_7)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setStyleSheet("color:rgb();\n"
"font: 87 12pt \"Arial Black\";")
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.cb_list_ports = QtWidgets.QComboBox(self.frame_7)
        self.cb_list_ports.setMinimumSize(QtCore.QSize(102, 30))
        self.cb_list_ports.setStyleSheet("QComboBox{\n"
"border: 3px solid #111111;\n"
"border-radius: 5px;\n"
"min-width:6em;\n"
"color: rgb(17,17,17);\n"
"front: 87 10pt \"Arial Black\";}\n"
"QComboBox::drop-down{\n"
"subcontrol-arigin:padding;\n"
"subcontrol-position: top right;\n"
"width: 15px;\n"
"border-left-width: 3px;\n"
"border-left-color: #111111;\n"
"border-left-style: solid;\n"
"border-top-right-radius: 4px;\n"
"border-bottom-right-radius: 4px}\n"
"QComboBox QAbstractItemView{\n"
"background: #2c2c2c;\n"
"selection-background-color: #8E9DAB;\n"
"color: #f5f8f7;}")
        self.cb_list_ports.setObjectName("cb_list_ports")
        self.horizontalLayout_6.addWidget(self.cb_list_ports)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setStyleSheet("color:rgb();\n"
"font: 87 12pt \"Arial Black\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.cb_list_baudrates = QtWidgets.QComboBox(self.frame_7)
        self.cb_list_baudrates.setMinimumSize(QtCore.QSize(102, 30))
        self.cb_list_baudrates.setStyleSheet("QComboBox{\n"
"border: 3px solid #111111;\n"
"border-radius: 5px;\n"
"min-width:6em;\n"
"color: rgb(17,17,17);\n"
"front: 87 10pt \"Arial Black\";}\n"
"QComboBox::drop-down{\n"
"subcontrol-arigin:padding;\n"
"subcontrol-position: top right;\n"
"width: 15px;\n"
"border-left-width: 3px;\n"
"border-left-color: #111111;\n"
"border-left-style: solid;\n"
"border-top-right-radius: 4px;\n"
"border-bottom-right-radius: 4px}\n"
"QComboBox QAbstractItemView{\n"
"background: #2c2c2c;\n"
"selection-background-color: #8E9DAB;\n"
"color: #f5f8f7;}")
        self.cb_list_baudrates.setObjectName("cb_list_baudrates")
        self.horizontalLayout_7.addWidget(self.cb_list_baudrates)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.bt_update = QtWidgets.QPushButton(self.frame_7)
        self.bt_update.setStyleSheet("QPushButton{\n"
"background-color: rgb(204,168,77);\n"
"font: 87 12pt\"Arial Black\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(36,63,98);\n"
"font: 87 12pt\"Arial Black\";\n"
"color:rgb(204,168,77);\n"
"}")
        self.bt_update.setObjectName("bt_update")
        self.horizontalLayout_8.addWidget(self.bt_update)
        self.bt_connect = QtWidgets.QPushButton(self.frame_7)
        self.bt_connect.setStyleSheet("QPushButton{\n"
"background-color: rgb(204,168,77);\n"
"font: 87 12pt\"Arial Black\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(36,63,98);\n"
"font: 87 12pt\"Arial Black\";\n"
"color:rgb(204,168,77);\n"
"}")
        self.bt_connect.setObjectName("bt_connect")
        self.horizontalLayout_8.addWidget(self.bt_connect)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.verticalLayout_12.addLayout(self.verticalLayout_10)
        self.verticalLayout_18.addLayout(self.verticalLayout_12)
        self.verticalLayout_21.addWidget(self.frame_7)
        self.line_3 = QtWidgets.QFrame(self.frame_8)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line_3.setFont(font)
        self.line_3.setStyleSheet("border: 16px solid rgb(20,49,83);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_21.addWidget(self.line_3)
        self.frame_2 = QtWidgets.QFrame(self.frame_8)
        self.frame_2.setStyleSheet("QFrame frame_2 {\n"
"    border: 2px solid red;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(7)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_6.setStyleSheet("color:rgb();\n"
"font: 87 12pt \"Arial Black\";\n"
"")
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_15.addWidget(self.label_6)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setStyleSheet("color:rgb();\n"
"font: 87 12pt \"Arial Black\";\n"
"")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.doubleSpinBox1 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBox1.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox1.setFont(font)
        self.doubleSpinBox1.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox1.setDecimals(5)
        self.doubleSpinBox1.setMaximum(1000.0)
        self.doubleSpinBox1.setObjectName("doubleSpinBox1")
        self.horizontalLayout_10.addWidget(self.doubleSpinBox1)
        self.verticalLayout_14.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setStyleSheet("color:rgb();\n"
"font: 87 12pt \"Arial Black\";\n"
"")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_11.addWidget(self.label_8)
        self.doubleSpinBox2 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBox2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox2.setFont(font)
        self.doubleSpinBox2.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox2.setDecimals(5)
        self.doubleSpinBox2.setMaximum(1000.0)
        self.doubleSpinBox2.setObjectName("doubleSpinBox2")
        self.horizontalLayout_11.addWidget(self.doubleSpinBox2)
        self.verticalLayout_14.addLayout(self.horizontalLayout_11)
        self.verticalLayout_15.addLayout(self.verticalLayout_14)
        self.verticalLayout_16.addLayout(self.verticalLayout_15)
        self.verticalLayout_17.addLayout(self.verticalLayout_16)
        self.verticalLayout_21.addWidget(self.frame_2)
        self.line = QtWidgets.QFrame(self.frame_8)
        self.line.setStyleSheet("border: 16px solid rgb(20,49,83);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_21.addWidget(self.line)
        self.frame_11 = QtWidgets.QFrame(self.frame_8)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.frame_11)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_10.setStyleSheet("color:rgb();\n"
"font: 87 12pt \"Arial Black\";\n"
"")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_8.addWidget(self.label_10)
        self.bt_temporizador = QtWidgets.QPushButton(self.frame_11)
        self.bt_temporizador.setStyleSheet("QPushButton{\n"
"background-color: rgb(204,168,77);\n"
"font: 87 12pt\"Arial Black\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(36,63,98);\n"
"font: 87 12pt\"Arial Black\";\n"
"color:rgb(204,168,77);\n"
"}")
        self.bt_temporizador.setObjectName("bt_temporizador")
        self.verticalLayout_8.addWidget(self.bt_temporizador)
        self.lcdCronometro = QtWidgets.QLCDNumber(self.frame_11)
        self.lcdCronometro.setMinimumSize(QtCore.QSize(0, 40))
        self.lcdCronometro.setObjectName("lcdCronometro")
        self.verticalLayout_8.addWidget(self.lcdCronometro)
        self.verticalLayout_20.addLayout(self.verticalLayout_8)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.bt_start = QtWidgets.QPushButton(self.frame_11)
        self.bt_start.setMinimumSize(QtCore.QSize(40, 0))
        self.bt_start.setStyleSheet("QPushButton{\n"
"background-color: rgb(204,168,77);\n"
"font: 87 12pt\"Arial Black\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(36,63,98);\n"
"font: 87 12pt\"Arial Black\";\n"
"color:rgb(204,168,77);\n"
"}")
        self.bt_start.setObjectName("bt_start")
        self.horizontalLayout_13.addWidget(self.bt_start)
        self.bt_stop = QtWidgets.QPushButton(self.frame_11)
        self.bt_stop.setMinimumSize(QtCore.QSize(40, 0))
        self.bt_stop.setStyleSheet("QPushButton{\n"
"background-color: rgb(204,168,77);\n"
"font: 87 12pt\"Arial Black\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(36,63,98);\n"
"font: 87 12pt\"Arial Black\";\n"
"color:rgb(204,168,77);\n"
"}")
        self.bt_stop.setObjectName("bt_stop")
        self.horizontalLayout_13.addWidget(self.bt_stop)
        self.bt_reset = QtWidgets.QPushButton(self.frame_11)
        self.bt_reset.setStyleSheet("QPushButton{\n"
"background-color: rgb(204,168,77);\n"
"font: 87 12pt\"Arial Black\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(36,63,98);\n"
"font: 87 12pt\"Arial Black\";\n"
"color:rgb(204,168,77);\n"
"}")
        self.bt_reset.setObjectName("bt_reset")
        self.horizontalLayout_13.addWidget(self.bt_reset)
        self.verticalLayout_20.addLayout(self.horizontalLayout_13)
        self.verticalLayout_22.addLayout(self.verticalLayout_20)
        self.verticalLayout_21.addWidget(self.frame_11)
        self.line_2 = QtWidgets.QFrame(self.frame_8)
        self.line_2.setStyleSheet("border: 16px solid rgb(20,49,83);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_21.addWidget(self.line_2)
        self.frame_4 = QtWidgets.QFrame(self.frame_8)
        self.frame_4.setStyleSheet("QFrame frame_2 {\n"
"    border: 2px solid red;\n"
"}\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setLineWidth(1)
        self.frame_4.setMidLineWidth(0)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_4.setStyleSheet("color:rgb();\n"
"font: 87 12pt \"Arial Black\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.bt_exportar = QtWidgets.QPushButton(self.frame_4)
        self.bt_exportar.setStyleSheet("QPushButton{\n"
"background-color: rgb(204,168,77);\n"
"font: 87 12pt\"Arial Black\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(36,63,98);\n"
"font: 87 12pt\"Arial Black\";\n"
"color:rgb(204,168,77);\n"
"}")
        self.bt_exportar.setObjectName("bt_exportar")
        self.verticalLayout_6.addWidget(self.bt_exportar)
        self.bt_disconnect = QtWidgets.QPushButton(self.frame_4)
        self.bt_disconnect.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.bt_disconnect.setFont(font)
        self.bt_disconnect.setStyleSheet("QPushButton{\n"
"background-color: rgb(204,168,77);\n"
"font: 78 12pt\"Arial Black\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(36,63,98);\n"
"font: 78 12pt\"Arial Black\";\n"
"color:rgb(204,168,77);\n"
"}")
        self.bt_disconnect.setObjectName("bt_disconnect")
        self.verticalLayout_6.addWidget(self.bt_disconnect)
        self.bt_Reinicio_Graficas = QtWidgets.QPushButton(self.frame_4)
        self.bt_Reinicio_Graficas.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.bt_Reinicio_Graficas.setFont(font)
        self.bt_Reinicio_Graficas.setStyleSheet("QPushButton{\n"
"background-color: rgb(204,168,77);\n"
"font: 78 12pt\"Arial Black\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(36,63,98);\n"
"font: 78 12pt\"Arial Black\";\n"
"color:rgb(204,168,77);\n"
"}")
        self.bt_Reinicio_Graficas.setObjectName("bt_Reinicio_Graficas")
        self.verticalLayout_6.addWidget(self.bt_Reinicio_Graficas)
        self.verticalLayout_21.addWidget(self.frame_4)
        self.label_2 = QtWidgets.QLabel(self.frame_8)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_21.addWidget(self.label_2)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_9 = QtWidgets.QFrame(self.frame_3)
        self.frame_9.setStyleSheet("background-color:rgb(245,248,246);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.graph_layout_humedad = QtWidgets.QVBoxLayout()
        self.graph_layout_humedad.setObjectName("graph_layout_humedad")
        self.verticalLayout_7.addLayout(self.graph_layout_humedad)
        self.horizontalLayout_3.addWidget(self.frame_9)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setStyleSheet("background-color:rgb(245,248,246);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.graph_layout_temperatura = QtWidgets.QVBoxLayout()
        self.graph_layout_temperatura.setObjectName("graph_layout_temperatura")
        self.verticalLayout_9.addLayout(self.graph_layout_temperatura)
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_10 = QtWidgets.QFrame(self.frame_3)
        self.frame_10.setStyleSheet("background-color:rgb(245,248,246);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.graph_layout_velocidad = QtWidgets.QVBoxLayout()
        self.graph_layout_velocidad.setObjectName("graph_layout_velocidad")
        self.verticalLayout_11.addLayout(self.graph_layout_velocidad)
        self.horizontalLayout_4.addWidget(self.frame_10)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setStyleSheet("background-color:rgb(245,248,246);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.graph_layout_friccion = QtWidgets.QVBoxLayout()
        self.graph_layout_friccion.setObjectName("graph_layout_friccion")
        self.verticalLayout_13.addLayout(self.graph_layout_friccion)
        self.horizontalLayout_4.addWidget(self.frame_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 5)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame_3)
        self.verticalLayout_3.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "Tribometro Pin On Disk"))
        self.label_5.setText(_translate("MainWindow", "Conexión del Ensayo"))
        self.label.setText(_translate("MainWindow", "Puerto Serial "))
        self.label_3.setText(_translate("MainWindow", "Velocidad Baudios"))
        self.bt_update.setText(_translate("MainWindow", "Actualizar"))
        self.bt_connect.setText(_translate("MainWindow", "Conectar"))
        self.label_6.setText(_translate("MainWindow", "Constantes de Ensayo"))
        self.label_7.setText(_translate("MainWindow", "Masa (kg)"))
        self.label_8.setText(_translate("MainWindow", "Radio (mm)"))
        self.label_10.setText(_translate("MainWindow", "Tiempo del Ensayo"))
        self.bt_temporizador.setText(_translate("MainWindow", "Temporizador"))
        self.bt_start.setText(_translate("MainWindow", "Inicio"))
        self.bt_stop.setText(_translate("MainWindow", "Pausar"))
        self.bt_reset.setText(_translate("MainWindow", "Reset"))
        self.label_4.setText(_translate("MainWindow", "Exportacion de Datos"))
        self.bt_exportar.setText(_translate("MainWindow", "Exportar"))
        self.bt_disconnect.setText(_translate("MainWindow", "Desconectar"))
        self.bt_Reinicio_Graficas.setText(_translate("MainWindow", "Reiniciar Graficas"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/Logo/Imagenes/Logo_investigacion.png\"/></p></body></html>"))
import Imagen_rc
import icon_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
